events {
    worker_connections 1024;
}

http {
    upstream produccion_frontend {
        server blue:3000;
    }

    upstream produccion_api {
        server blue:8000;
    }

    server {
        listen 80;
        server_name localhost;

        location ~* ^/(auth|productos|ordenes|chat|faq|perfiles|static)(/|$) {
            proxy_pass http://produccion_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location / {
            proxy_pass http://produccion_frontend;
            proxy_set_header Host $host;
            add_header X-Ambiente "blue" always;
        }
    }
}
